[project]
name = "project-2-guess-the-number-game-python-project-computer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
